name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.5 (2.5.7 is not yet supported)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5
    - name: Copy config file
      run: cp .env.local.template .env.local
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Rspec
      run: rspec
      env:
        AWS_REGION: "eu-central-1"
        AWS_ACCESS_KEY_ID: "dummy"
        AWS_SECRET_ACCESS_KEY: "dummy"
    - name: Run rubocop
      uses: gimenete/rubocop-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
